id: A8BA31593
title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in Eight
  Chapters'
type: translation
pechas:
- IBE752086
- I4417BA8C
- I69CE6A66
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:36:15.630928
  last_modified_at: 2023-01-04 11:36:15.630941
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IBE752086/2D4C: 8DB9
  I4417BA8C/C24E: 8DB9
  I69CE6A66/1290: 8DB9
